# mcp_server_basic.py - Basic MCP Server for Image Analysis
# This server provides basic image analysis tools for learning MCP integration

import io
import uuid
from pathlib import Path
import base64
from typing import Dict, List, Tuple, Optional

from fastapi import FastAPI, Request, HTTPException, UploadFile, File, Form
from fastapi.responses import StreamingResponse
from transformers import AutoProcessor, AutoModelForCausalLM, OwlViTProcessor, OwlViTForObjectDetection
from PIL import Image, ImageDraw, ImageFont
import uvicorn
import torch
import numpy as np
import json
import asyncio

app = FastAPI()

# --------------------------------------------------------------
# Load Moondream (vision‑language model) - lighter version
# --------------------------------------------------------------
MODEL_NAME = "vikhyatk/moondream2"
processor = AutoProcessor.from_pretrained(MODEL_NAME, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    dtype=torch.float16,
    device_map="auto",
    trust_remote_code=True
)

# --------------------------------------------------------------
# Load OwlViT for object detection
# --------------------------------------------------------------
DETECTION_MODEL_NAME = "google/owlvit-base-patch32"
detection_processor = OwlViTProcessor.from_pretrained(DETECTION_MODEL_NAME)
detection_model = OwlViTForObjectDetection.from_pretrained(DETECTION_MODEL_NAME)

# --------------------------------------------------------------
# Resource storage for MCP resource sharing
# --------------------------------------------------------------
resources: Dict[str, str] = {}  # resource_id -> base64_image_data

# --------------------------------------------------------------
# MCP info endpoint
# --------------------------------------------------------------
@app.get("/mcp/info")
async def mcp_info():
    return {
        "protocol_version": "2.0",
        "supported_encodings": ["json"],
        "tls_required": False,
    }

@app.post("/mcp/initialize")
async def mcp_initialize(request: Request):
    """MCP initialization endpoint"""
    data = await request.json()
    return {
        "jsonrpc": "2.0",
        "id": data.get("id"),
        "result": {
            "protocolVersion": "2.0",
            "capabilities": {
                "tools": {}
            },
            "serverInfo": {
                "name": "basic-image-server",
                "version": "1.0.0"
            }
        }
    }

# --------------------------------------------------------------
# Helper: run Moondream on an image + optional question
# --------------------------------------------------------------
def run_moondream(image_bytes: bytes, question: str | None) -> str:
    """Return a description or answer generated by Moondream."""
    pil_img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    prompt = question if question else "Describe this image."
    inputs = processor(pil_img, prompt, return_tensors="pt").to(model.device)

    generated_ids = model.generate(**inputs, max_new_tokens=256, do_sample=False)
    output_text = processor.decode(generated_ids[0], skip_special_tokens=True)
    answer = output_text.replace(prompt, "").strip()
    return answer

# --------------------------------------------------------------
# Helper: detect objects using OwlViT
# --------------------------------------------------------------
def detect_objects(image_bytes: bytes, text_queries: List[str]) -> Tuple[List[dict], Image.Image]:
    """Detect objects in image and return bounding boxes with annotated image."""
    pil_img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    
    # Process image and text queries
    inputs = detection_processor(text=text_queries, images=pil_img, return_tensors="pt")
    
    # Run detection
    with torch.no_grad():
        outputs = detection_model(**inputs)
    
    # Process results
    target_sizes = torch.Tensor([pil_img.size[::-1]])
    results = detection_processor.post_process_object_detection(outputs=outputs, target_sizes=target_sizes, threshold=0.1)
    
    boxes = results[0]["boxes"]
    scores = results[0]["scores"]
    labels = results[0]["labels"]
    
    # Create annotated image
    draw = ImageDraw.Draw(pil_img)
    
    # Try to load a font, fallback to default if not available
    try:
        font = ImageFont.truetype("/System/Library/Fonts/Arial.ttf", 20)
    except:
        font = ImageFont.load_default()
    
    detections = []
    colors = ['red', 'blue', 'green', 'yellow', 'purple', 'orange', 'pink', 'cyan']
    
    for i, (box, score, label) in enumerate(zip(boxes, scores, labels)):
        if score > 0.1:  # Confidence threshold
            x1, y1, x2, y2 = box.tolist()
            query_text = text_queries[label]
            color = colors[i % len(colors)]
            
            # Draw bounding box
            draw.rectangle([x1, y1, x2, y2], outline=color, width=3)
            
            # Draw label
            label_text = f"{query_text}: {score:.2f}"
            draw.text((x1, y1-25), label_text, fill=color, font=font)
            
            detections.append({
                "query": query_text,
                "confidence": float(score),
                "bbox": [float(x1), float(y1), float(x2), float(y2)],
                "position": f"center at ({int((x1+x2)/2)}, {int((y1+y2)/2)})"
            })
    
    return detections, pil_img

# --------------------------------------------------------------
# Helper: convert PIL image to base64
# --------------------------------------------------------------
def pil_to_base64(pil_img: Image.Image) -> str:
    """Convert PIL image to base64 string."""
    buffer = io.BytesIO()
    pil_img.save(buffer, format="PNG")
    return base64.b64encode(buffer.getvalue()).decode('utf-8')

# --------------------------------------------------------------
# MCP Resource endpoints
# --------------------------------------------------------------
@app.post("/resources/list")
async def list_resources():
    """List available image resources."""
    return {
        "resources": [
            {
                "uri": f"image://{resource_id}",
                "name": f"annotated_image_{resource_id[:8]}",
                "description": f"Annotated image resource {resource_id[:8]}"
            }
            for resource_id in resources.keys()
        ]
    }

@app.get("/resources/read/{resource_id}")
async def read_resource(resource_id: str):
    """Retrieve a specific annotated image resource."""
    if resource_id in resources:
        return {
            "contents": [
                {
                    "uri": f"image://{resource_id}",
                    "mimeType": "image/png",
                    "text": resources[resource_id]
                }
            ]
        }
    raise HTTPException(status_code=404, detail="Resource not found")

# --------------------------------------------------------------
# Tool endpoints
# --------------------------------------------------------------
@app.post("/tools/list")
async def list_tools():
    """List available tools."""
    return {
        "tools": [
            {
                "name": "find_item_in_image",
                "description": "Find and describe a specific item in an image with position details",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "image_base64": {"type": "string", "description": "Base64 encoded image data"},
                        "item_description": {"type": "string", "description": "Description of item to find (e.g., 'umbrella', 'car', 'person')"}
                    },
                    "required": ["image_base64", "item_description"]
                }
            },
            {
                "name": "describe_image",
                "description": "Get a general description of an image using Moondream",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "image_base64": {"type": "string", "description": "Base64 encoded image data"},
                        "question": {"type": "string", "description": "Optional specific question about the image"}
                    },
                    "required": ["image_base64"]
                }
            },
            {
                "name": "annotate_object",
                "description": "Detect and annotate objects in an image with bounding boxes",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "image_base64": {"type": "string", "description": "Base64 encoded image data"},
                        "object_queries": {"type": "array", "items": {"type": "string"}, "description": "List of objects to detect (e.g., ['umbrella', 'person', 'car'])"}
                    },
                    "required": ["image_base64", "object_queries"]
                }
            }
        ]
    }

@app.post("/tools/call")
async def call_tool(request: Request):
    """Call a specific tool."""
    try:
        body = await request.json()
        tool_name = body.get("name")
        arguments = body.get("arguments", {})
        
        if tool_name == "find_item_in_image":
            image_base64 = arguments.get("image_base64", "")
            item_description = arguments.get("item_description", "")
            
            # Decode base64 image
            image_bytes = base64.b64decode(image_base64)
            
            # Use Moondream to find and describe the item
            question = f"Find and describe the {item_description} in this image. Where is it located?"
            answer = run_moondream(image_bytes, question)
            
            # Also try object detection for more precise location
            detections, annotated_img = detect_objects(image_bytes, [item_description])
            
            result = {
                "answer": answer,
                "item_description": item_description,
                "detections": detections,
                "annotated_image_base64": pil_to_base64(annotated_img),
                "success": True
            }
            
            return {"result": result}
            
        elif tool_name == "describe_image":
            image_base64 = arguments.get("image_base64", "")
            question = arguments.get("question", "Describe this image.")
            
            # Decode base64 image
            image_bytes = base64.b64decode(image_base64)
            
            # Run Moondream analysis
            answer = run_moondream(image_bytes, question)
            
            return {
                "result": {
                    "answer": answer,
                    "question": question,
                    "success": True
                }
            }
            
        elif tool_name == "annotate_object":
            image_base64 = arguments.get("image_base64", "")
            object_queries = arguments.get("object_queries", [])
            
            # Decode base64 image
            image_bytes = base64.b64decode(image_base64)
            
            # Detect objects and create annotated image
            detections, annotated_img = detect_objects(image_bytes, object_queries)
            
            return {
                "result": {
                    "detections": detections,
                    "annotated_image_base64": pil_to_base64(annotated_img),
                    "object_queries": object_queries,
                    "success": True
                }
            }
        else:
            raise HTTPException(status_code=400, detail=f"Unknown tool: {tool_name}")
            
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Tool call failed: {e}")

# --------------------------------------------------------------
# SSE endpoint for MCP communication
# --------------------------------------------------------------
@app.get("/mcp/sse")
@app.head("/mcp/sse")
async def mcp_sse():
    """Server-Sent Events endpoint for MCP communication"""
    async def event_generator():
        # Send initial connection message
        yield f"data: {json.dumps({'type': 'connection', 'status': 'connected'})}\n\n"
        
        # Keep connection alive
        while True:
            await asyncio.sleep(30)  # Send heartbeat every 30 seconds
            yield f"data: {json.dumps({'type': 'heartbeat', 'timestamp': 'keepalive'})}\n\n"
    
    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "Access-Control-Allow-Origin": "*",
            "Access-Control-Allow-Headers": "*",
        }
    )

# --------------------------------------------------------------
# Run the server
# --------------------------------------------------------------
if __name__ == "__main__":
    print("🚀 Starting Basic MCP Server for Image Analysis...")
    print("📋 Available tools: find_item_in_image, describe_image, annotate_object")
    print("🌐 Server running on http://localhost:8001")
    print("🛑 Press Ctrl+C to stop")
    
    uvicorn.run(
        "mcp_server_basic:app",
        host="0.0.0.0",
        port=8001,
        log_level="info",
    )
